config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  get 'sessions/new'
  get 'users/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :badge_rewards, only: :index
  resources :badges, only: :index

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
    resources :gists, only: %i[new create], shallow: true
  end

  resources :feedbacks, only: %i[new create], shallow: true

  namespace :admin do
    resources :gists, only: :index
    
    resources :badges

    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, except: [:index], shallow: true do
        resources :answers, except: [:index], shallow: true
      end
    end
  end
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>    
  <span class="nav-admin-title"><%= t('.panel')%> </span>

  <span>
    <p class="nav-admin-user">
      <%= t(".welcome", first_name: current_user.first_name, last_name: current_user.last_name) %>
      <% if current_user.is_a?(Admin) %>
        <p> 
          <%= link_to t('helpers.admin_panel'), admin_tests_path %> |
          <%= link_to t('.gists'), admin_gists_path %> |
          <%= link_to t('.badges'), admin_badges_path %> |
          <%= link_to t('.feedback'), new_feedback_path %> |
          <%= link_to t(".logout"), destroy_user_session_path, method: :delete%>
        </p>
      <% else %>
        <p> <%= link_to t(".logout"), destroy_user_session_path, method: :delete%> <p> 
      <% end %>
    </p>
  </span>
</nav>