config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  get 'sessions/new'
  get 'users/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :badge_rewards, only: :index
  resources :badges, only: :index

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
    resources :gists, only: %i[new create], shallow: true
  end

  resources :feedbacks, only: %i[new create], shallow: true

  namespace :admin do
    resources :gists, only: :index
    
    resources :badges

    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, except: [:index], shallow: true do
        resources :answers, except: [:index], shallow: true
      end
    end
  end
end

app/models/gist.rb
# frozen_string_literal: true

class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :user, uniqueness: { scope: :question }
  validates :gist_url, presence: true, on: :update
end

app/controllers/admin/gists_controller.rb
# frozen_string_literal: true

class Admin::GistsController < ApplicationController
  def index
    @gists = Gist.all
  end
end

app/controllers/gists_controller.rb
# frozen_string_literal: true

class GistsController < ApplicationController
  before_action :find_test_passage, only: %i[new create]

  def new
    @gist = Gist.new
  end

  def create
    result = GistQuestionService.new(@test_passage.current_question).call

    if result.success?
      flash_options = { notice: t('.success', gist_url: gist_url(result)) }
    else
      flash_options = { alert: t('.failure') }
    end

    redirect_to @test_passage, flash_options
  end

  private

  def gist_url(gist)
    view_context.link_to(gist.html_url, gist.html_url, target: '_blank')
  end

  def find_test_passage
    @test_passage = TestPassage.find(params[:test_passage_id])
  end
end

app/helpers/admin/gists_helper.rb
module Admin::GistsHelper
end

app/views/admin/gists/_gist.html.erb
<tr>
  <td><%= link_to(gist.gist_url, gist.gist_url, target: '_blank') %></td>
  <td><%= gist.user.email %></td>
  <td><%= link_to truncate(gist.question.body, length: 25), admin_question_path(gist.question) %></td>
</tr>

app/views/admin/gists/index.html.erb
<h2><%= t('.header') %></h2>
  <table class="table">>
  <tr>
    <th><%= t('.gist_url') %></th>
    <th><%= t('.user') %></th>
    <th><%= t('.question') %></th>
  </tr>
  
  <%= render @gists %>
</table>
<%= link_to t('back', scope: 'helpers.submit'), admin_tests_path, class: 'btn btn-primary mt-1' %>