config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  get 'sessions/new'
  get 'users/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :badge_rewards, only: :index
  resources :badges, only: :index

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
    resources :gists, only: %i[new create], shallow: true
  end

  resources :feedbacks, only: %i[new create], shallow: true

  namespace :admin do
    resources :gists, only: :index
    
    resources :badges

    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, except: [:index], shallow: true do
        resources :answers, except: [:index], shallow: true
      end
    end
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :test_passages, class_name: 'TestPassage', foreign_key: :current_question_id, dependent: :destroy

  validates :body, presence: true

  delegate :author, to: :test

  scope :following, ->(question) { order(:id).where('id > ?', question.id) }
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  SUCCESS_PERCENT = 85
  MIN_TO_SEC = 60

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_current_question

  validate :expired_test, on: :update


  delegate :questions, :title, :time_to_pass, :category, :level, to: :test
  delegate :passed_tests_with_level, to: :user, prefix: true
  delegate :passed_tests_with_category, to: :user, prefix: true

  scope :passed, -> { where('passed_percent >= ?', SUCCESS_PERCENT) }
  scope :by_level, ->(level) { includes(:test).where(tests: { level: level }) }
  scope :by_category, ->(category) { includes(:test).where(tests: { category: category }) }

  def completed?
    expired? || current_question.nil?
  end

  def questions_count
    questions.count
  end

  def good_result?
    result_percent > SUCCESS_PERCENT
  end

  def result_percent
    ((correct_questions * 100.00) / questions_count).round
  end

  def accept_params=(answer_ids)
    @answer_ids = answer_ids

    self.correct_questions += 1 if correct_answer?(answer_ids)
  end

  def current_question_number
    questions_count - questions.following(current_question).count
  end

  def expired?
    return false unless time_to_pass.present?

    Time.now > deadline_time
  end

  def deadline_time
    created_at + time_to_pass.minutes
  end

  def attempts
    user.test_passes(test_id).count
  end

  def update_result
    return unless completed?

    update!(passed_percent: result_percent)
  end

  private

  def expired_test
    errors.add(:base, 'test is expired') if expired?

  end

  def set_current_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    if answer_ids.present?
      correct_answers.ids.sort == answer_ids.map(&:to_i).sort
    else
      false
    end
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    return questions.first unless current_question.present?

    questions.following(current_question).first
  end
end

app/controllers/test_passages_controller.rb
# frozen_string_literal: true

class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result]

  def show; end

  def result; end

  def update

    @test_passage.update(accept_params: params[:answer_ids])

    if @test_passage.update_result
      TestRewardingService.new(@test_passage).call if @test_passage.good_result?

      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
# frozen_string_literal: true

module TestPassagesHelper
  def result_title(test_passage)
    t('.correct', correct_questions: test_passage.correct_questions, questions_count: test_passage.questions_count)
  end

  def result_color(test_passage)
    test_passage.good_result? ? 'green' : 'red'
  end

  def result_text(test_passage)
    if test_passage.good_result?
      t('.passed', result_percent: test_passage.result_percent)
    else
      t('.unpassed', result_percent: test_passage.result_percent)
    end
  end

  def view_current_question(test_passage)
    t('.current_question', question_num: test_passage.current_question_number, questions_count: test_passage.questions_count)
  end
end

app/views/test_passages/result.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6">
    <h1><%= t('.header', title: @test_passage.test.title) %></h1>

    <p>
    <%= result_title(@test_passage) %>
    </p>
    <p style="color:<%= result_color(@test_passage) %>">
    <%= result_text(@test_passage) %>
    <p>

    <p><%= link_to t('back', scope: 'helpers.submit'), tests_path, class: 'btn btn-primary mt-1'  %> </p>
  </div>
</div>

app/views/test_passages/show.html.erb
<div class="row justify-content-left mt-3">
  <div class="form-group">
    <h1><%= t('.header', title: @test_passage.title) %></h1>
    <p>
      <b><%= @test_passage.current_question.body %></b>
    </p>
    <p>
      <div class="progress">
        <%= content_tag :div, view_current_question(@test_passage),
                              class: 'progress-bar', 
                              role: "progressbar",
                              data: { current_question: @test_passage.current_question_number,
                                      questions_count: @test_passage.questions_count }, 
                              'aria-valuemin': '0', 
                              'aria-valuemax': '100'  %>      
      </div>
      <% if @test_passage.time_to_pass.present? %>
        <%= content_tag :div, nil, 
                              class: "caption",
                              data: { deadline: @test_passage.deadline_time.to_i,
                                      test_id: @test_passage.id } %>
      <% end %>
    </p>
    <%= form_with url: test_passage_path(@test_passage), class: "submit_form", id: 'my-form', local: true, method: :put do |form| %>
      <div class="form-check">
        <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b| %>
          <p>
            <%= b.check_box id: "answer_ids_#{b.object.id}", class: 'form-check-input' %>
            <%= b.label %>
          </p>  
        <% end %>
      </div>
      <p><%= link_to t('.gist_question'), test_passage_gists_path(@test_passage), method: :post %></p>
      <p><%= form.submit class: 'btn btn-primary mt-1' %></p>
      <% end %>
  </div>
</div>