config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'users/sessions' }

  get 'sessions/new'
  get 'users/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :badge_rewards, only: :index
  resources :badges, only: :index

  resources :test_passages, only: %i[show update] do
    member do
      get :result
    end
    resources :gists, only: %i[new create], shallow: true
  end

  resources :feedbacks, only: %i[new create], shallow: true

  namespace :admin do
    resources :gists, only: :index
    
    resources :badges

    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, except: [:index], shallow: true do
        resources :answers, except: [:index], shallow: true
      end
    end
  end
end

app/views/shared/_errors.html.erb
  <% if resource.present? && resource.errors.any? %>
    <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
      <h2><%= t('shared.errors.header', count: resource.errors.count)  %></h2>


      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>

app/views/shared/_flash.html.erb
<%= flash_messages %>

app/views/shared/_header_nav.html.erb
<% if current_user.is_a?(Admin) %>
  <nav class="navbar navbar-light bg-light">
    <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
    <li class="nav-item">
      <a class="nav-link" href="#">Trololo</a>
    </li>
  </nav>
<% else %>
  <nav class="navbar navbar-light bg-light">
    <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
  <span class="navbar-text">

    <% if user_signed_in? %>
      <p class="nav_user">
      <%= t(".welcome", first_name: current_user.first_name, last_name: current_user.last_name) %>

      <% if current_user.is_a?(Admin) %>
        <p> 
          <%= link_to t('helpers.admin_panel'), admin_tests_path %> |
          <%= link_to t('admin.nav.feedback'), new_feedback_path %> |
          <%= link_to t('.badges'), badges_path %> |
          <%= link_to t('.my_badges'), badge_rewards_path %> |
          <%= link_to t(".logout"), destroy_user_session_path, method: :delete%>
        </p>
      <% else %>
        <p> 
            <%= link_to t('.feedback'), new_feedback_path %> |
            <%= link_to t(".logout"), destroy_user_session_path, method: :delete%> 
        </p> 
      <% end %>
      </p>
    <% else %>
      <p class="nav guest"> <%= link_to t('helpers.sign_in'), new_user_session_path, method: :get %> | <%=link_to t('helpers.registration'), new_user_registration_path, method: :get%> </p>
    <% end %>
  </span>
</nav>